'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Check,Clock3,ArrowRight,ShieldCheck,LogOut,RefreshCw,ChevronLeft,CheckCircle2,XCircle,LoaderCircle} from 'lucide-react';
import {choose,complete,type PublicQuestion,type Picks} from '../lib/model';
type Bank={id:string;name:string;description:string;total:number;available:number;done:number};
type ReviewQuestion=PublicQuestion&{answers?:string[][];notes?:string;codexExplanation?:string;disputed?:boolean;correct?:boolean};
type Session={id:string;bank:string;version:number;startedAt:number;submittedAt:number|null;score:number|null;picks:Picks;questions:ReviewQuestion[]};
type User={name:string;email:string;owner:boolean;status:string};
type History={id:string;bank:string;started_at:number;submitted_at:number|null;score:number|null};
type Member={id:string;email:string;name:string;status:string;created_at:number;owner:boolean};
type AdminData={members:Member[];quarantined:{id:string;section:string;number:number;page:number;answers:string[][];bank:string;issue:string}[]};
async function api(path='',body?:unknown){const response=await fetch('/api/gre'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json() as any;if(!response.ok)throw new Error(data.error||'操作未完成，請重試。');return data}
function time(ms:number){const sec=Math.max(0,Math.floor(ms/1000));return `${Math.floor(sec/60).toString().padStart(2,'0')}:${(sec%60).toString().padStart(2,'0')}`}
const statusLabel:Record<string,string>={pending:'等待審核',approved:'已核准',rejected:'未獲核准',new:'尚未申請'};
export default function Practice({signedIn,signin,signout,initialBanks}:{signedIn:boolean;signin:string;signout:string;initialBanks:Bank[]}){
 const [banks,setBanks]=useState(initialBanks),[user,setUser]=useState<User|null>(null),[history,setHistory]=useState<History[]>([]),[selected,setSelected]=useState('B'),[session,setSession]=useState<Session|null>(null),[admin,setAdmin]=useState<AdminData|null>(null),[view,setView]=useState<'home'|'practice'|'admin'>('home'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saving,setSaving]=useState(0),[now,setNow]=useState(Date.now()),[confirmSubmit,setConfirmSubmit]=useState(false);
 const sessionRef=useRef<Session|null>(null),queue=useRef(Promise.resolve()),mounted=useRef(true);
 function updateSession(s:Session){sessionRef.current=s;setSession(s)}
 async function load(){const d=await api();setUser(d.user);setBanks(d.banks);setHistory(d.history)}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{mounted.current=true;if(signedIn)void run(load);return()=>{mounted.current=false}},[signedIn]);
 useEffect(()=>{if(!session||session.submittedAt)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[session?.id,session?.submittedAt]);
 useEffect(()=>{const prevent=(event:BeforeUnloadEvent)=>{if(saving){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[saving]);
 async function start(bank=selected){await run(async()=>{updateSession(await api('',{action:'start',bank}));setSelected(bank);setView('practice');setConfirmSubmit(false);window.scrollTo(0,0)})}
 async function resume(id:string){await run(async()=>{updateSession(await api('?action=session&id='+encodeURIComponent(id)));setView('practice');setConfirmSubmit(false);window.scrollTo(0,0)})}
 function pick(q:ReviewQuestion,option:string){const old=sessionRef.current;if(!old||old.submittedAt)return;const picks={...old.picks,[q.id]:choose(q,old.picks[q.id]||[],option)};updateSession({...old,picks});setSaving(n=>n+1);setError('');queue.current=queue.current.then(async()=>{const current=sessionRef.current;if(!current||current.id!==old.id)return;try{const result=await api('',{action:'save',id:old.id,version:current.version,picks});const latest=sessionRef.current!;updateSession({...latest,version:result.version})}catch(e){setError((e as Error).message)}finally{setSaving(n=>n-1)}})}
 async function submit(){await run(async()=>{await queue.current;const s=sessionRef.current!;const result=await api('',{action:'submit',id:s.id,version:s.version,picks:s.picks});updateSession(result);setConfirmSubmit(false);await load();window.scrollTo(0,0)})}
 async function openAdmin(){await run(async()=>{setAdmin(await api('?action=admin'));setView('admin')})}
 async function review(id:string,status:string){await run(async()=>{await api('',{action:'review',id,status});setAdmin(await api('?action=admin'))})}
 // The optional browser tool reads the same persisted progress shown in the interface.
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool||!user||user.status!=='approved')return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_gre_progress',description:'Read the signed-in learner’s saved B, C and D progress. Does not start or submit practice.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},async execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('This tool accepts an empty object.');const d=await api();setBanks(d.banks);return {banks:d.banks}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[user?.email,user?.status]);
 const answered=session?.questions.filter(q=>complete(q,session.picks[q.id]||[])).length||0;
 const missing=session?.questions.map((q,i)=>({q,i})).filter(({q})=>!complete(q,session.picks[q.id]||[]))||[];
 const missingLinks=missing.length>0?<div className="missing-questions" role="status"><strong>尚未完成 {missing.length} 題</strong><span>{missing.map(({q,i})=><a href={'#q-'+q.id} key={q.id} aria-label={'跳至尚未完成的第 '+(i+1)+' 題'}>第 {i+1} 題</a>)}</span><small>點題號返回補答；多空格與等價題須選齊答案。</small></div>:<p className="all-complete"><CheckCircle2 size={15}/>15 題皆已完成，可以交卷。</p>;
 const isReview=!!session?.submittedAt;const chosen=banks.find(b=>b.id===selected)!;
 const allowed=user?.status==='approved';const done=banks.reduce((n,b)=>n+b.done,0);const total=banks.reduce((n,b)=>n+b.available,0);
 return <div className="shell">
  <header className="topbar"><button className="brand plain" onClick={()=>{if(!saving){setView('home');if(signedIn)void run(load)}}} aria-label="返回題庫"><b>G<span>15</span></b><span>GRE 練習室<small>VERBAL PRACTICE</small></span></button><nav>{user?.owner&&<button className={'nav-button '+(view==='admin'?'active':'')} onClick={openAdmin}><ShieldCheck size={16}/>管理審核</button>}{signedIn&&<a className="nav-button" href={signout} target="_top"><LogOut size={16}/><span>登出</span></a>}{!signedIn&&<span className="topnote">每天一回，累積你的實力</span>}</nav></header>
  {error&&<div className="error" role="alert"><span>{error}</span><button className="plain" onClick={()=>void run(load)}>重新載入帳號</button></div>}
  <main>
  {view==='home'&&<>
   <div className="intro-row"><div><div className="eyebrow">YOUR DAILY FIFTEEN</div><h1>選一本題庫，<br/>專注接下來的 <em>15 題。</em></h1><p className="intro">完成一回，查看答案、講義解析與用時。</p></div>{allowed&&<div className="overall"><span>我的累積進度</span><strong>{done.toLocaleString()}<small> / {total.toLocaleString()}</small></strong><div className="bar"><i style={{width:`${done/total*100}%`}}/></div><small>不重複已作答題數 · 跨裝置保存</small></div>}</div>
   <div className="section-head"><h2>選擇題庫</h2><span>每回 15 題 · 優先練習未作答題目</span></div>
   <div className="bank-grid">{banks.map(b=><button className={'bank-card '+(selected===b.id?'selected':'')} onClick={()=>setSelected(b.id)} key={b.id} aria-pressed={selected===b.id}><div className="bank-card-top"><span className="bank-letter">{b.id}</span><span className={'radio '+(selected===b.id?'checked':'')}>{selected===b.id&&<Check size={14}/>}</span></div><div><small>QUESTION BANK {b.id}</small><h2>{b.name}</h2><p>{b.description}</p></div><div className="bank-numbers"><span>總題數 <b>{b.total}</b></span><span>已作答 <b>{allowed?b.done:'—'}</b></span></div><div className="bar"><i style={{width:`${b.done/b.available*100}%`}}/></div><div className="card-foot">{b.available} 題可練習 <span>{b.total>b.available?`${b.total-b.available} 題答案待核對`:`${allowed?Math.round(b.done/b.available*100):0}% 完成`}</span></div></button>)}</div>
   {!signedIn?<section className="access"><div><h2>登入後申請練習權限</h2><p>經管理員核准後，即可使用三組題庫並保存進度。</p></div><a className="primary" href={signin} target="_top">使用 ChatGPT 登入 <ArrowRight size={17}/></a></section>
   :!user?<section className="panel"><p>{busy?'正在載入帳號…':'無法載入帳號，請重試。'}</p><button className="secondary" disabled={busy} onClick={()=>void run(load)}>重新載入</button></section>
   :!allowed?<section className="access"><div><h2>{user.status==='new'?'申請加入 GRE 練習室':statusLabel[user.status]}</h2><p>{user.email} · {user.status==='rejected'?'請聯絡管理員確認存取權限。':user.status==='pending'?'你的申請已送出。核准後，重新整理即可開始。':'送出申請後，由管理員核准你的帳號。'}</p></div>{user.status==='new'?<button className="primary" disabled={busy} onClick={()=>void run(async()=>{await api('',{action:'apply'});await load()})}>送出申請 <ArrowRight size={17}/></button>:<button className="secondary light" disabled={busy} onClick={()=>void run(load)}><RefreshCw size={16}/>查看審核狀態</button>}</section>
   :<section className="start-strip"><div><strong>{selected} · {chosen.name}</strong><p>未作答題不足 15 題時，會加入已作答題複習。開始即計時。</p></div><button className="primary" disabled={busy} onClick={()=>void start()}>{busy?<LoaderCircle className="spin" size={18}/>:<BookOpen size={18}/>}開始 / 繼續 15 題 <ArrowRight size={18}/></button></section>}
   {allowed&&<section className="history"><div className="section-head"><h2>我的練習紀錄</h2><span>{user?.email}</span></div>{history.length===0?<div className="empty">還沒有練習紀錄。選擇題庫，完成你的第一回。</div>:<div className="history-list">{history.map(h=><button key={h.id} disabled={busy} className="history-row" onClick={()=>void resume(h.id)}><span className="mini-bank">{h.bank}</span><span><b>{h.submitted_at?'15 題練習':'尚未交卷'}</b><small>{new Date(h.started_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></span><span className="history-score">{h.submitted_at?<><b>{h.score} / 15</b><small><Clock3 size={13}/>{time(h.submitted_at-h.started_at)}</small></>:<b>繼續作答</b>}</span><ArrowRight size={16}/></button>)}</div>}</section>}
  </>}
  {view==='practice'&&session&&<>
   <button className="back plain" disabled={saving>0} onClick={()=>{setView('home');void run(load)}}><ChevronLeft size={17}/>返回題庫</button>
   <div className="session-heading"><div><div className="eyebrow">BANK {session.bank} / FIFTEEN QUESTIONS</div><h1>{isReview?'完成一回，回看你的思路。':'給自己一段專注的時間。'}</h1><p className="muted">{isReview?'逐題核對答案與解析；[codex] 為補充撰寫，其他內容取自講義。':'請完成全部 15 題，再交卷查看答案。'}</p></div></div>
   {isReview&&<div className="results-summary"><div><span>答對題數</span><strong>{session.score}<small> / 15</small></strong></div><div><span>正確率</span><strong>{Math.round((session.score||0)/15*100)}<small>%</small></strong></div><div><span>作答時間</span><strong>{time(session.submittedAt!-session.startedAt)}</strong></div><div><span>{session.bank} 題庫已作答</span><strong>{banks.find(b=>b.id===session.bank)?.done}<small> / {banks.find(b=>b.id===session.bank)?.available}</small></strong></div></div>}
   <div className="practice-layout"><aside className="session-sidebar"><div className="sidebar-card"><div className="eyebrow">{isReview?'本回結果':'本回進度'}</div><div className="timer"><Clock3 size={21}/><span>{time((session.submittedAt||now)-session.startedAt)}</span></div><p>{isReview?`答對 ${session.score} / 15 題`:`已完成 ${answered} / 15 題`}</p><div className="question-nav">{session.questions.map((q,i)=><a key={q.id} href={'#q-'+q.id} aria-label={'前往第 '+(i+1)+' 題'} className={isReview?(q.correct?'right':'wrong'):complete(q,session.picks[q.id]||[])?'filled':''}>{i+1}</a>)}</div><small className="save-status" aria-live="polite">{isReview?'成績與進度已保存':saving?'正在儲存答案…':error?'儲存遇到問題，請重試':'答案自動儲存'}</small>{!isReview&&<>{missingLinks}<button className="primary full" disabled={answered!==15||busy||saving>0} onClick={()=>setConfirmSubmit(true)}>完成並交卷</button><small>計時包含離開頁面的時間。<br/>重新整理可繼續同一回。</small></>}</div>{isReview&&<button className="primary full" disabled={busy} onClick={()=>void start(session.bank)}>再練習 15 題</button>}</aside>
   <div className="questions">{session.questions.map((q,i)=><article className={'question '+(isReview?(q.correct?'correct-card':'incorrect-card'):'')} id={'q-'+q.id} key={q.id}><div className="q-meta"><span><b>{String(i+1).padStart(2,'0')}</b> / 15</span><span>{q.section} · 第 {q.number} 題</span>{isReview&&(q.correct?<span className="result-tag good"><CheckCircle2 size={15}/>答對</span>:<span className="result-tag bad"><XCircle size={15}/>答錯</span>)}</div><p className="stem" lang="en">{q.stem}</p><div className="q-instruction">{q.kind==='equivalence'?'等價填空 · 請選出兩個答案':q.blanks>1?`${q.blanks} 格填空 · 每格選一個答案`:'單格填空 · 請選出一個答案'}</div><div className={'option-groups groups-'+(q.kind==='completion'?q.blanks:1)}>{(q.kind==='completion'&&q.blanks>1?['ABC','DEF','GHI'].slice(0,q.blanks):['ABCDEFGHI']).map((group,gi)=><fieldset key={group}><legend>{q.blanks>1?'Blank ('+['i','ii','iii'][gi]+')':'選項'}</legend>{q.options.filter(o=>group.includes(o.id)).map(o=>{const picked=(session.picks[q.id]||[]).includes(o.id);const right=isReview&&q.answers?.some(a=>a.includes(o.id));return <label className={'option '+(picked?'picked ':'')+(right?'answer-right ':'')+(isReview&&picked&&!right?'answer-wrong':'')} key={o.id}><input type={q.kind==='equivalence'?'checkbox':'radio'} name={q.id+'-'+group} checked={picked} disabled={isReview||busy} onChange={()=>pick(q,o.id)}/><span className="option-letter">{o.id}</span><span lang="en">{o.text}</span>{right&&<Check size={16}/>}</label>})}</fieldset>)}</div>
   {isReview&&<section className="explanation"><div className="answer-line"><span>你的答案 <b>{session.picks[q.id]?.join('、')||'未作答'}</b></span><span>參考答案 <b>{q.answers?.map(a=>a.join('、')).join(' 或 ')}</b></span></div>{q.disputed&&<p className="notice">講義標示為爭議題，本題為六選二，A、B、E 中任選兩項均計為正確。</p>}<h3>{q.codexExplanation?"解題解析":"講義解析與補充"}</h3>{q.codexExplanation&&<div className="codex-explanation"><span>[codex]</span><p>{q.codexExplanation}</p></div>}{q.notes&&q.notes.length>15?<p className="source-notes">{q.notes}</p>:!q.codexExplanation?<p className="muted">此題的講義與答案表未附文字解析；目前提供原始參考答案。</p>:null}{q.editorialNote&&<p className="source-reference">整理註記：{q.editorialNote}</p>}<p className="source-reference">來源：{q.bank} 題本 PDF 第 {q.page} 頁 · {q.section} 第 {q.number} 題。答案依配套答案表。</p></section>}</article>)}
   {!isReview&&<div className="end-submit-wrap">{missingLinks}<div className="end-submit"><span>已完成 {answered} / 15 題</span><button className="primary" disabled={answered!==15||busy||saving>0} onClick={()=>setConfirmSubmit(true)}>交卷並查看結果 <ArrowRight size={17}/></button></div></div>}</div></div>
  </>}
  {view==='admin'&&admin&&<><button className="back plain" onClick={()=>setView('home')}><ChevronLeft size={17}/>返回題庫</button><div className="eyebrow">ACCESS MANAGEMENT</div><h1>使用者審核</h1><p className="intro">核准後即可練習 B、C、D 題庫。撤回權限後，題庫與個人成績都會停止開放。</p><div className="section-head"><h2>等待審核 · {admin.members.filter(m=>m.status==='pending').length}</h2><button className="secondary" disabled={busy} onClick={openAdmin}><RefreshCw size={15}/>重新整理</button></div><div className="members">{admin.members.filter(m=>!m.owner).length===0?<div className="empty">目前沒有使用者申請。</div>:admin.members.filter(m=>!m.owner).sort((a,b)=>Number(b.status==='pending')-Number(a.status==='pending')).map(m=><div className="member" key={m.id}><div><b>{m.name}</b><small>{m.email}</small><small>申請：{new Date(m.created_at).toLocaleString('zh-TW')}</small></div><span className={'badge '+m.status}>{statusLabel[m.status]}</span><div className="member-actions">{m.status!=='approved'&&<button className="primary" disabled={busy} onClick={()=>void review(m.id,'approved')}>核准</button>}{m.status!=='rejected'&&<button className="secondary" disabled={busy} onClick={()=>void review(m.id,'rejected')}>{m.status==='approved'?'撤回權限':'拒絕'}</button>}</div></div>)}</div><section className="panel"><h2>題庫校驗</h2><p className="muted">已辨識 {banks.reduce((n,b)=>n+b.total,0)} 題，可練習 {total} 題。以下題目的答案或題幹有疑義，暫不出題。</p>{admin.quarantined.map(q=><p key={q.id}><b>{q.bank} · {q.section} 第 {q.number} 題</b> — 答案表：{q.answers.flat().join('、')}；題本 PDF 第 {q.page} 頁。<br/><span className="muted">{q.issue}</span></p>)}</section></>}
  </main><footer>GRE 練習室 <span>B / C / D · 每回 15 題</span></footer>
  {confirmSubmit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="submit-title"><h2 id="submit-title">交出這 15 題？</h2><p>交卷後會停止計時並顯示答案與講義解析，這回的答案將無法修改。</p><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirmSubmit(false)}>繼續檢查</button><button className="primary" autoFocus disabled={busy||saving>0} onClick={()=>void submit()}>{busy?'正在交卷…':'確認交卷'}</button></div></section></div>}
 </div>
}

